Workspace/GameAffinityGen/Web_GameAffinity/Controllers/BuscarController.cs
using GameAffinityGen.ApplicationCore.IRepository.GameAffinity;
using Microsoft.AspNetCore.Mvc;
using Web_GameAffinity.Models;
// Using nuestro
using GameAffinityGen.ApplicationCore.CEN.GameAffinity;
using GameAffinityGen.ApplicationCore.EN.GameAffinity;
using GameAffinityGen.Infraestructure.Repository.GameAffinity;

namespace Web_GameAffinity.Controllers
{
    public class BuscarController : Controller
    {
        public IActionResult Buscar()
        {
            VideojuegoRepository videojuegoRepository = new VideojuegoRepository();
            EmpresaRepository empresaRepository = new EmpresaRepository();
            IndividuoRepository individuoRepository = new IndividuoRepository();

            VideojuegoCEN videojuegoCEN = new VideojuegoCEN(videojuegoRepository);
            EmpresaCEN empresaCEN = new EmpresaCEN(empresaRepository);
            IndividuoCEN individuoCEN = new IndividuoCEN(individuoRepository);

            var viewModel = new BuscarViewModel
            {
                Videojuegos = videojuegoCEN.GetAll(0, -1),
                Empresas = empresaCEN.GetAll(0, -1),
                Personas = individuoCEN.GetAll(0, -1)
            };

            return View(viewModel);
        }
    }
}

Workspace/GameAffinityGen/Web_GameAffinity/Controllers/EmpresaController.cs
using GameAffinityGen.ApplicationCore.CEN.GameAffinity;
using GameAffinityGen.ApplicationCore.EN.GameAffinity;
using GameAffinityGen.Infraestructure.Repository.GameAffinity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Web_GameAffinity.Assembler;
using Web_GameAffinity.Models;
using NHibernate;
using NHibernate.Proxy;

namespace Web_GameAffinity.Controllers
{
    public class EmpresaController : BasicController
    {

        private readonly IWebHostEnvironment _webHost;

        public EmpresaController(IWebHostEnvironment webHost)
        {
            _webHost = webHost;
        }

        // GET: EmpresaController
        public ActionResult Index()
        {
            SessionInitialize();
            EmpresaRepository empresaRepository = new EmpresaRepository();
            EmpresaCEN empresaCEN = new EmpresaCEN(empresaRepository);

            IList<EmpresaEN> listEN = empresaCEN.GetAll(0, -1);

            IEnumerable<EmpresaViewModel> listaEmpresas = new EmpresaAssembler().ConvertirListaENtoViewModel(listEN).ToList();
            SessionClose();

            return View(listaEmpresas);
        }

        // GET: EmpresaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EmpresaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(EmpresaViewModel empresa)
        {
            string fileName = await FileHelper.GetFileName(empresa.Imagen, _webHost.WebRootPath);

            try
            {
                EmpresaRepository repository = new EmpresaRepository();
                EmpresaCEN cen = new EmpresaCEN(repository);
                cen.New_(
                    empresa.Nombre,
                    empresa.Descripcion,
                    0,
                    fileName
                );
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmpresaController/Edit/5
        public ActionResult Edit(int id)
        {
            SessionInitialize();
            EmpresaRepository empresaRepository = new EmpresaRepository(session);
            EmpresaCEN empresaCEN = new EmpresaCEN(empresaRepository);

            EmpresaEN empresaEn = empresaCEN.GetByOID(id);
            EmpresaViewModel empresaView = new EmpresaAssembler().ConvertirENToViewModel(empresaEn);

            SessionClose();
            return View(empresaView);
        }

        // POST: EmpresaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, EmpresaViewModel empresa)
        {
            try
            {
                EmpresaRepository empresaRepository = new EmpresaRepository();
                EmpresaCEN empresaCEN = new EmpresaCEN(empresaRepository);

                string fileName = await FileHelper.GetFileName(empresa.Imagen, _webHost.WebRootPath);

                empresaCEN.Modify(
                    id,
                    empresa.Nombre,
                    empresa.Descripcion,
                    0.0f,
                    fileName
                );

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmpresaController/Delete/5
        public ActionResult Delete(int id)
        {
            EmpresaRepository empresaRepository = new EmpresaRepository();
            EmpresaCEN empresaCEN = new EmpresaCEN(empresaRepository);
            empresaCEN.Destroy(id);
            return RedirectToAction(nameof(Index));
        }

        // POST: EmpresaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //codigo silva
        public ActionResult Details(int id)
        {

            SessionInitialize();

            if (id == 0)
            {
                SessionClose();
                return new EmptyResult();
            }

            EmpresaRepository empRepo = new EmpresaRepository(session);
            EmpresaCEN empCen = new EmpresaCEN(empRepo);

            // Obtienes la empresa por su ID
            EmpresaEN empresaEN = empCen.GetByOID(id);
            System.Diagnostics.Debug.WriteLine(id);

            if (empresaEN.Videojuegos != null)
            {
                NHibernateUtil.Initialize(empresaEN.Videojuegos);
            }

            if (empresaEN.Individuos != null)
            {
                NHibernateUtil.Initialize(empresaEN.Individuos);
            }

            // Creas el modelo que pasas a la vista
            DetailsEmpresaViewModel model = new EmpresaAssembler().ConvertirENToDetailsViewModel(empresaEN);

            SessionClose();

            return View(model);
        }
    }


}

Workspace/GameAffinityGen/Web_GameAffinity/Controllers/ListaController.cs
using GameAffinityGen.ApplicationCore.CEN.GameAffinity;
using GameAffinityGen.ApplicationCore.EN.GameAffinity;
using GameAffinityGen.Infraestructure.Repository.GameAffinity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Web_GameAffinity.Assembler;
using Web_GameAffinity.Models;
using NHibernate;
using GameAffinityGen.ApplicationCore.CP.GameAffinity;
using GameAffinityGen.Infraestructure.CP;

namespace Web_GameAffinity.Controllers
{
    public class ListaController : BasicController
    {
        private readonly IWebHostEnvironment _webHost;

        public ListaController(IWebHostEnvironment webHost)
        {
            _webHost = webHost;
        }

        // GET: ListaController
        public ActionResult Index()
        {
            var user = HttpContext.Session.Get<ConfiguracionPerfilViewModel>("user");

            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModeradorRepository repo = new ModeradorRepository();
                ModeradorCEN cen = new ModeradorCEN(repo);
                ModeradorEN esModerador = cen.GetByOID(user.id);

                if (esModerador == null)
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SessionInitialize();
            ListaRepository listaRepository = new ListaRepository(session);
            ListaCEN listaCEN = new ListaCEN(listaRepository);

            IList<ListaEN> listEN = listaCEN.GetAll(0, -1);

            IEnumerable<ListaViewModel> listLists = new ListaAssembler().ConvertirListENToViewModel(listEN).ToList();
            SessionClose();

            return View(listLists);
        }



        // GET: ListaController/Details/5
        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return new EmptyResult();
            }

            // Inicializamos la sesión
            SessionInitialize();

            // Repositorios y CEN necesarios
            ListaRepository listRepo = new ListaRepository(session);
            VideojuegoRepository videojuegoRepo = new VideojuegoRepository(session);

            ListaCEN listCEN = new ListaCEN(listRepo);
            VideojuegoCEN videojuegoCEN = new VideojuegoCEN(videojuegoRepo);

            // Obtenemos la lista por ID
            ListaEN listEN = listCEN.GetByOID(id);
            if (listEN != null)
            {
                NHibernateUtil.Initialize(listEN.Videojuegos); // Inicializamos los videojuegos asociados a la lista
            }

            // Obtenemos todos los videojuegos de la base de datos
            IList<VideojuegoEN> todosLosVideojuegos = videojuegoCEN.GetAll(0, -1);

            // Convertimos la entidad a modelo de vista
            ListaViewModel listView = new ListaAssembler().ConvertirENToViewModel(listEN);

            // Añadimos todos los videojuegos al modelo de vista
            listView.TodosLosVideojuegos = todosLosVideojuegos;

            // Cerramos la sesión
            SessionClose();

            // Devolvemos la vista con el modelo actualizado
            return View(listView);
        }




        // GET: ListaController/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: ListaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ListaViewModel list)
        {
            string fileName = await FileHelper.GetFileName(list.Imagen, _webHost.WebRootPath);

            try
            {
                // Obtener el usuario logueado desde la sesión
                var userSession = HttpContext.Session.Get<PerfilViewModel>("user");
                if (userSession == null || userSession.id <= 0)
                {
                    // Redirigir a la página de login si no hay usuario logueado
                    return RedirectToAction("Login", "Registrado");
                }

                // Crear la lista con el ID del usuario logueado como autor
                ListaRepository listRepo = new ListaRepository();
                ListaCEN listCEN = new ListaCEN(listRepo);
                listCEN.New_(
                    list.Nombre,
                    list.Descripcion,
                    list.Por_defecto,
                    userSession.id, // Usar el ID del usuario logueado como autor
                    fileName
                );

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // GET: ListaController/Edit/5
        public ActionResult Edit(int id)
        {
            SessionInitialize();
            ListaRepository listRepo = new ListaRepository(session);
            ListaCEN listCEN = new ListaCEN(listRepo);

            ListaEN listEN = listCEN.GetByOID(id);
            Console.WriteLine(listEN);
            ListaViewModel listView = new ListaAssembler().ConvertirENToViewModel(listEN);

            SessionClose();
            return View(listView);
        }

        // POST: ListaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, ListaViewModel list)
        {
            string fileName = await FileHelper.GetFileName(list.Imagen, _webHost.WebRootPath);

            try
            {
                ListaRepository listRepo = new ListaRepository();
                ListaCEN listCEN = new ListaCEN(listRepo);
                listCEN.Modify(
                    list.Id,
                    list.Nombre,
                    list.Descripcion,
                    list.Por_defecto,
                    fileName
                );
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ListaController/Delete/5
        public ActionResult Delete(int id)
        {
            ListaRepository listRepo = new ListaRepository();
            ListaCEN listCEN = new ListaCEN(listRepo);
            listCEN.Destroy(id);
            return RedirectToAction(nameof(Index));
        }

        // POST: ListaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }




        // POST: ListaController/AnyadirVideojuego
        [HttpPost]
        public ActionResult AnyadirVideojuego(int listaId, int videojuegoId)
        {
            try
            {
                if (listaId <= 0 || videojuegoId <= 0)
                {
                    return BadRequest("IDs inválidos");
                }

                // Inicializamos la sesión
                SessionInitialize();

                // Repositorio y CEN
                ListaRepository listRepo = new ListaRepository(session);
                ListaCEN listCEN = new ListaCEN(listRepo);
                ListaCP listCP = new ListaCP(new SessionCPNHibernate());
                listCP.AnyadirJuego(listaId, new List<int> { }, videojuegoId);
                //listCEN.AnyadirVideojuego(listaId, new List<int> { }, videojuegoId);


                // Llamamos al método de negocio para añadir el videojuego
                //listCEN.AnyadirVideojuego(listaId, new List<int> { videojuegoId});

                ListaEN lista = listCEN.GetByOID(listaId);
                // Cerramos la sesión
                SessionClose();

                // Redirigir a los detalles de la lista tras añadir el videojuego
                return RedirectToAction("Details", new { id = listaId });
            }
            catch (Exception ex)
            {
                // Manejo de errores
                SessionClose();
                return View("Error", new { message = ex.Message });
            }
        }

        // DELETE: ListaController/EliminarVideojuego
        public ActionResult EliminarVideojuego(int listaId, int videojuegoId)
        {
            try
            {
                if (listaId <= 0 || videojuegoId <= 0)
                {
                    return BadRequest("IDs inválidos");
                }

                // Inicializamos la sesión
                SessionInitialize();

                // Repositorio y CEN
                ListaRepository listRepo = new ListaRepository(session);
                ListaCEN listCEN = new ListaCEN(listRepo);
                ListaCP listCP = new ListaCP(new SessionCPNHibernate());
                listCP.EliminarJuego(listaId, new List<int> { }, videojuegoId);
                //listCEN.AnyadirVideojuego(listaId, new List<int> { }, videojuegoId);


                // Llamamos al método de negocio para añadir el videojuego
                //listCEN.AnyadirVideojuego(listaId, new List<int> { videojuegoId});

                ListaEN lista = listCEN.GetByOID(listaId);
                // Cerramos la sesión
                SessionClose();

                // Redirigir a los detalles de la lista tras añadir el videojuego
                return RedirectToAction("Details", new { id = listaId });
            }
            catch (Exception ex)
            {
                // Manejo de errores
                SessionClose();
                return View("Error", new { message = ex.Message });
            }
        }
    }
}

Workspace/GameAffinityGen/Web_GameAffinity/Views/Shared/ResenyaCard.cshtml
@model Web_GameAffinity.Models.ResenyaViewModel

@{
    var user = Context.Session.Get<ConfiguracionPerfilViewModel>("user");
    InteraccionViewModel userInteraccion = null;
    int userId = -1;
    string iconolike = "bi bi-hand-thumbs-up";
    string iconodislike = "bi bi-hand-thumbs-down";
    if(user != null)
    {
        Console.WriteLine("user is not null");
        userId = user.id;


        userInteraccion = Model.Interacciones.FirstOrDefault<InteraccionViewModel>(r => r.IdAutor == userId);

        if ( userInteraccion != null ) {
            if ( userInteraccion.Liked ) {
                Console.WriteLine("interactionLiked");
                iconolike += "-fill";
            }

            else if ( userInteraccion.Disliked ) {
                Console.WriteLine("interactionDisLiked");
                iconodislike += "-fill";
            }
        }
    }
    Console.WriteLine(iconolike);
    Console.WriteLine(iconodislike);
}

<div class="resenya card bg-light mb-5 row" style="min-width: 20rem;">
    <div class="card-header">
        <h5>@Html.DisplayFor(model => model.Titulo)</h5>
        <span class="nota" style="margin: 0">
            @Html.DisplayFor(model => model.Valoracion)
        </span>
  </div>
    
    <div class="card-body">
        <p class="card-text">@Html.DisplayFor(model => model.Texto)</p>
        <p>
            Autor:
            <a asp-action="DetailsUsuario" asp-controller="Registrado" asp-route-id="@Model.IdAutor" class="card-text">
                @Html.DisplayFor(model => model.NombreAutor)
            </a>
        </p>
    </div>

    <div class="card-footer bg-light text-center">
        <form 
            asp-controller="Interaccion" 
            asp-action="InteraccionCambia" 
            method="post">
            <input type="number" name="idusuario" value="@userId" hidden />
            <input type="number" name="idresenya" value="@Model.Id" hidden />
            <input type="number" name="operation" value="0" hidden />
            <input type="text" name="contr" value="juego" hidden />
            <button type="submit" class="btn btn-light mr-1">
                <i class="@iconolike"></i><span class="ml-1">@Model.Likes_contador</span>
            </button>
        </form>
        

        <form asp-controller="Interaccion" asp-action="InteraccionCambia" method="post">
            <input type="number" name="idusuario" value="@userId" hidden />
            <input type="number" name="idresenya" value="@Model.Id" hidden />
            <input type="number" name="operation" value="1" hidden />
            <input type="text" name="contr" value="juego" hidden />
            <button type="submit" class="btn btn-light mr-1">
                <i class="@iconodislike"></i><span class="ml-1">@Model.Dislikes_contador</span>
            </button>
        </form>
        
    </div>
</div>

Workspace/GameAffinityGen/Web_GameAffinity/Views/Shared/ResenyaCardList.cshtml
@model Web_GameAffinity.Models.ResenyaViewModel


<div class="resenya card bg-light mb-5 row" style="min-width: 20rem;">
    <div class="card-header">
        <h5>@Html.DisplayFor(model => model.Titulo)</h5>
        <span class="nota" style="margin: 0">
            @Html.DisplayFor(model => model.Valoracion)
        </span>
    </div>
    
    <div class="card-body">
        <p class="card-text">@Html.DisplayFor(model => model.Texto)</p>
        <p>
            Autor:
            <a asp-action="DetailsUsuario" asp-controller="Registrado" asp-route-id="@Model.Id" class="card-text">
                @Html.DisplayFor(model => model.NombreAutor)
            </a>
        </p>
    </div>

    <div class="card-footer bg-light text-center">
        <button class="btn btn-light mr-1">
            <i class="bi bi-hand-thumbs-up"></i>
            <span class="ml-1">@Html.DisplayFor(model => model.Likes_contador)</span>
        </button>
        
        <button class="btn btn-light mr-1">
            <i class="bi bi-hand-thumbs-down"></i>
            <span class="ml-1">@Html.DisplayFor(model => model.Dislikes_contador)</span>
        </button>
    </div>
</div>

Workspace/GameAffinityGen/Web_GameAffinity/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using GameAffinityGen.ApplicationCore.CEN.GameAffinity
@using GameAffinityGen.ApplicationCore.EN.GameAffinity
@using GameAffinityGen.Infraestructure.Repository.GameAffinity

<!DOCTYPE html>
<html lang="en">

@using Microsoft.AspNetCore.Http

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web_GameAffinity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://bootstrapbuildspace.sfo2.cdn.digitaloceanspaces.com//NNZsowkXSnlP/qvlFaWYfdVfD/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web_GameAffinity.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Chakra+Petch:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">
    @* iconos de bootstrap tio *@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><h1 class="nav-title">GameAffinity</h1></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <!--ESTO LO VE TO KISKI-->
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Buscar" asp-action="Buscar">Buscar</a>
                        </li>
                        <!--<li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>  -->
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Videojuego" asp-action="Index">Videojuegos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Empresa" asp-action="Index">Empresas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Individuo" asp-action="Index">Individuos</a>
                        </li>


                            <!--ESTO LO VE ALGUIEN SI NO SE HA REGISTRADO O INICIADO SESIÓN-->
                        @if (Context.Session.Get<ConfiguracionPerfilViewModel>("user") == null)
                        {
                            <ul class="navbar-nav flex-grow-1 justify-content-end">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Registrado" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Registrado" asp-action="Registro">Registro</a>
                                </li>
                            </ul>
                        }
                        else
                        {
                            ModeradorRepository repo = new ModeradorRepository();
                            ModeradorCEN cen = new ModeradorCEN(repo);
                            var user = Context.Session.Get<ConfiguracionPerfilViewModel>("user");
                            ModeradorEN esModerador = cen.GetByOID(user.id);



                                <!--ESTO LO VE UN MODERADOR-->
                            @if(esModerador != null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Lista" asp-action="Index">Listas</a>
                                </li>                                
                            }
                            
                                <!--ESTO LO VE UN USUARIO REGISTRADO QUE NO ES MODERADOR Y LOS MODERADORES-->
                                    

                            <ul class="navbar-nav flex-grow-1 justify-content-end">

                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Registrado" asp-action="Details">Perfil</a>
                                </li>
                                <li class="nav-item">
                                    <form method="post" asp-area="" asp-controller="Registrado" asp-action="Logout">
                                        <button type="submit" class="nav-link btn btn-link text-light">Cerrar Sesión</button>
                                    </form> 
                                </li>
                            </ul>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="container text-light">
            &copy; 2024 - Web_GameAffinity - <a class="text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Workspace/GameAffinityGen/Web_GameAffinity/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web_GameAffinity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web_GameAffinity.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Web_GameAffinity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Workspace/GameAffinityGen/Web_GameAffinity/Views/Shared/empresaCard.cshtml
@model GameAffinityGen.ApplicationCore.EN.GameAffinity.EmpresaEN

<a class="col-4 col-md-3 col-lg-2 videogame" asp-action="Details" asp-controller="Empresa" asp-route-id="@Model.Id">
    <section class="videogameScore">
        <span class="score">@Html.DisplayFor(modelItem => Model.Nota)</span>
    </section>
    <img src=@Model.Img class="videogameImage" onerror="this.src='/Images/missing_img.jpg';" />
    <span class="videogameName">
        @Html.DisplayFor(modelItem => Model.Nombre)
    </span>
</a>

Workspace/GameAffinityGen/Web_GameAffinity/Views/Shared/empresaCardList.cshtml
@model IList<GameAffinityGen.ApplicationCore.EN.GameAffinity.EmpresaEN>

<div class="videogameList row">
    @foreach (var item in Model)
    {
        @Html.Partial("empresaCard", item)
    }
</div>

Workspace/GameAffinityGen/Web_GameAffinity/Views/Shared/individuoCard.cshtml
@model GameAffinityGen.ApplicationCore.EN.GameAffinity.IndividuoEN

<a class="col-4 col-md-3 col-lg-2 videogame" asp-action="Details" asp-controller="Individuo" asp-route-id="@Model.Id">
    <img src=@Model.Img class="videogameImage" onerror="this.src='/Images/missing_img.jpg';" />
    <span class="videogameName">
        @Model.Nombre
    </span>
</a>

Workspace/GameAffinityGen/Web_GameAffinity/Views/Shared/listaCardList.cshtml
@model IList<GameAffinityGen.ApplicationCore.EN.GameAffinity.ListaEN>

<div class="videogameList row">
    @foreach (var item in Model)
    {
        @Html.Partial("listaCard", item)
    }
</div>